/**
 * MeReviewsApiClient — authenticated customer reviews endpoints.
 *
 * Task v0.19.c / MOBILE_API_CONTRACT.md v1.5.6 §3:
 *   GET    /v1/public/me/reviews?page=&pageSize=       → ReviewListResponse
 *   POST   /v1/public/me/reviews  (Idempotency-Key)   → ReviewDto (201)
 *   DELETE /v1/public/me/reviews/:id                  → 204
 *
 * IMPORTANT: This client MUST use the intercepted httpClient (auth + 401-refresh).
 * The /v1/public/me/* namespace is authenticated despite the "public" prefix —
 * this is the established convention across B's API surface.
 *
 * Separate from ListingReviewsApiClient which wraps rawHttpClient for the
 * no-auth /v1/public/listings/:id/reviews route.
 *
 * Response bodies are Zod-validated at the boundary — same pattern as
 * MeInspectionsApiClient and MeDocumentsApiClient.
 */

import type { AxiosInstance } from 'axios';
import {
  ReviewListResponseSchema,
  ReviewDtoSchema,
  type ReviewListResponse,
  type ReviewDto,
  type CreateReviewInput,
} from '@behbehani-cpo/shared-types';

// ─── Client ───────────────────────────────────────────────────────────────────

export class MeReviewsApiClient {
  /**
   * @param axios Intercepted AxiosInstance (httpClient). Auth header + 401-refresh
   *              are handled transparently by the request/response interceptors.
   */
  constructor(private readonly axios: AxiosInstance) {}

  /**
   * Lists the authenticated customer's own reviews (paginated, newest first).
   * GET /v1/public/me/reviews?page=&pageSize=
   *
   * Response includes averageRating + ratingHistogram — same shape as the
   * public listing-reviews endpoint, scoped to the caller's own reviews.
   */
  async list(params: { page?: number; pageSize?: number } = {}): Promise<ReviewListResponse> {
    const res = await this.axios.get<unknown>('/v1/public/me/reviews', {
      params: {
        page: params.page ?? 1,
        pageSize: params.pageSize ?? 20,
      },
    });
    return ReviewListResponseSchema.parse(res.data);
  }

  /**
   * Submits a new review for a completed transaction target.
   * POST /v1/public/me/reviews
   *
   * Sends an Idempotency-Key header to prevent duplicate submissions on
   * network retry — callers MUST supply a stable UUID per submission attempt.
   *
   * Server rejects with:
   *   403 REVIEW_TARGET_NOT_REVIEWABLE — customer hasn't completed the required
   *       transaction for this target.
   *   409 REVIEW_ALREADY_SUBMITTED     — compound unique (customer, target) violated.
   *
   * @param input   Validated CreateReviewInput — target + rating + title + body.
   * @param idempotencyKey  Stable UUID for this submission (UUIDv4 generated by caller).
   */
  async create(input: CreateReviewInput, idempotencyKey: string): Promise<ReviewDto> {
    const res = await this.axios.post<unknown>('/v1/public/me/reviews', input, {
      headers: { 'Idempotency-Key': idempotencyKey },
    });
    return ReviewDtoSchema.parse(res.data);
  }

  /**
   * Deletes the authenticated customer's review by ID.
   * DELETE /v1/public/me/reviews/:id
   *
   * Returns 204 No Content on success. Throws AxiosError on:
   *   404 REVIEW_NOT_FOUND — unknown ID or not owned by caller.
   *
   * @param id  Review UUID.
   */
  async delete(id: string): Promise<void> {
    await this.axios.delete(`/v1/public/me/reviews/${encodeURIComponent(id)}`);
  }
}
