const { NxAppWebpackPlugin } = require('@nx/webpack/app-plugin');
const { join } = require('path');

module.exports = {
  output: {
    path: join(__dirname, 'dist'),
    clean: true,
    ...(process.env.NODE_ENV !== 'production' && {
      devtoolModuleFilenameTemplate: '[absolute-resource-path]',
    }),
  },
  plugins: [
    new NxAppWebpackPlugin({
      target: 'node',
      compiler: 'tsc',
      main: './src/main.ts',
      tsConfig: './tsconfig.app.json',
      assets: [
        './src/assets',
        // v1.5.16 — Demo rich-media (walk-around + 360) assets served via
        // app.use('/static/demo-media', express.static(...)). Generated by
        // scripts/generate-rich-media-demo.mjs and committed to repo. Copied
        // into dist/seed/demo-media so the same __dirname-relative lookup
        // works in both dev (swc-node serving src/) and prod (node dist/).
        {
          input: './src/seed/demo-media',
          glob: '**/*',
          output: 'seed/demo-media',
        },
      ],
      optimization: false,
      outputHashing: 'none',
      generatePackageJson: false,
      sourceMap: true,
    }),
  ],
};
